services:

  db:
    image: postgres:15
    container_name: postgre_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ruffo2319.
      POSTGRES_DB: microservices-hospital
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "5007:5007"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  alerts_service:
    build: ./alerts_service
    container_name: alerts_service
    ports:
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  devices_service:
    build: ./devices_service
    container_name: devices_service
    ports:
      - "5003:5003"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  locations_service:
    build: ./locations_service
    container_name: locations_service
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  metrics_service:
    build: ./metrics_service
    container_name: metrics_service
    ports:
      - "5004:5004"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  reports_service:
    build: ./reports_service
    container_name: reports_service
    ports:
      - "5006:5006"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  users_service:
    build: ./users_service
    container_name: users_service
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:ruffo2319.@db:5432/microservices-hospital

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - users_service
      - locations_service
      - devices_service
      - metrics_service
      - alerts_service
      - reports_service

volumes:
  postgres_data: